name: Scrape YC Jobs and Send to n8n

on:
  schedule:
    - cron: '0 2 * * *'  # 每天 UTC 02:00
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r scraper/requirements.txt

      - name: Run scraper
        run: |
          cd scraper
          python scraper.py --output jobs.json

      - name: Send to n8n webhook
        run: |
          cd scraper
          curl -X POST https://darrickxue.app.n8n.cloud/webhook-test/54d03a17-c07e-47a0-972c-79f2f7306119 \
          -H "Content-Type: application/json" \
          --data @jobs.json
